# Generated by Django 5.2.5 on 2025-09-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('N', 'Normal'), ('G', 'Gold')], default='N', max_length=1)),
                ('card_duration_time', models.FloatField(default=10)),
                ('credit', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('game_image', models.ImageField(default='', upload_to='main_app/static/uploads/')),
                ('game_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='kid',
            name='card',
        ),
        migrations.RemoveField(
            model_name='kidgame',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='kidgame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='kidgame',
            name='kid',
        ),
        migrations.CreateModel(
            name='kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('kid_image', models.ImageField(default='', upload_to='main_app/static/uploads/')),
                ('fk_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cards')),
            ],
        ),
        migrations.CreateModel(
            name='kids_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('fk_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.employees')),
                ('fk_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.games')),
                ('fk_kid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.kids')),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Kid',
        ),
        migrations.DeleteModel(
            name='KidGame',
        ),
    ]
