# Generated by Django 5.2.5 on 2025-09-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_kids_games_fk_employee_id_kids_games_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='credit',
        ),
        migrations.AddField(
            model_name='kids',
            name='credit',
            field=models.FloatField(default=0.0),
        ),
    ]
