# Generated by Django 5.2.5 on 2025-09-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_cards_credit_kids_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kids',
            name='fk_card_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.cards'),
        ),
    ]
