# Generated by Django 5.2.5 on 2025-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_kids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids_games',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='kids_games',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='kids_games',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
