# Generated by Django 5.2.5 on 2025-09-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_kids_games_create_date_alter_kids_games_end_time_and_more'),
    ]

    operations = [
    ]
