# Generated by Django 5.2.5 on 2025-09-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20250919_2003'),
    ]

    operations = [
    ]
