# Generated by Django 5.2.5 on 2025-09-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20250919_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='kids',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kids',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
