# Generated by Django 5.2.6 on 2025-09-22 17:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_kids_hash_kids_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='game_image'),
        ),
        migrations.AlterField(
            model_name='kids',
            name='kid_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='kid_image'),
        ),
    ]
